"""add created_activities_count to users

Revision ID: 351d988424d5
Revises: 32319b42e986
Create Date: 2026-05-26 16:05:08.306094

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "351d988424d5"
down_revision = "32319b42e986"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "created_activities_count", sa.Integer(), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "created_activities_count")
    # ### end Alembic commands ###
