"""add avatar bio telegram_id user_role to user

Revision ID: 3c3be2d9f552
Revises: ebd84883d56f
Create Date: 2026-03-25 21:21:34.873540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c3be2d9f552'
down_revision = 'ebd84883d56f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE userrole AS ENUM ('client', 'moderator')")
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('telegram_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('user_role', sa.Enum('client', 'moderator', name='userrole'), server_default='client', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_role')
    op.drop_column('users', 'telegram_id')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar')
    op.execute("DROP TYPE userrole")
    # ### end Alembic commands ###
