"""add_is_banned_to_users

Revision ID: 75cf31e57fdb
Revises: b1611fd23fd1
Create Date: 2026-06-01 02:21:58.266191

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "75cf31e57fdb"
down_revision = "b1611fd23fd1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_banned", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_banned")
    # ### end Alembic commands ###
