"""update created_at field in user model

Revision ID: d490dc355111
Revises: 3c3be2d9f552
Create Date: 2026-03-25 23:48:14.215970

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d490dc355111"
down_revision = "3c3be2d9f552"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DateTime(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DateTime(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
