"""add banner field to user model

Revision ID: f35cda60c92b
Revises: d490dc355111
Create Date: 2026-03-26 00:19:07.320627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35cda60c92b'
down_revision = 'd490dc355111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('banner', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banner')
    # ### end Alembic commands ###
